### ISSUE TITLE
[Trivial/Easy fix] Lang is not showing in the itemGroup

### ISSUE THREAD

**Issue by FlickySH** [MatrexsVigil/harvestcraft#183]
Pretty self explained.
![image](https://user-images.githubusercontent.com/33214461/38047886-786a140c-32cc-11e8-82f9-ce6c80477d49.png)

**Comment by ProjectGR** [comment]
It seems the en_us.lang file has been encoded in **UTF-8-BOM** which seems to add three characters (`´++`) in the start of the file which subsequently breaks the whatever is on the first line, which happens to be the `itemGroup.harvestcraft=HarvestCraft`. Simply re-encoding the file in **UTF-8** will remove the characters and fix the problem.

 #198 Should fix it

**Comment by ghost** [comment]
![2018-04-15_16 01 28](https://user-images.githubusercontent.com/10398117/38779285-58949618-40c6-11e8-81c0-b13a3539ccb7.png)




[assets.lang.en_us.zip](https://github.com/MatrexsVigil/harvestcraft/files/1912918/assets.lang.en_us.zip)

**Comment by KenyMylankca** [comment]
yeah please fix this

**Comment by KenyMylankca** [comment]
that pull request doesn't fix this. you must put the itemGroup.harvestcraft=HarvestCraft to the **second** line in the lang file to fix this. i tried it, and it works. then you can close this issue. just move the first line to the second line in the lang file.
example:
[en_us.txt](https://github.com/MatrexsVigil/harvestcraft/files/3237174/en_us.txt)
(it's .lang, just made it .txt to upload here)
